- 51-android.rules
Hi,
Product Id of my OnePlus One was missing, so mtp doesn't work.
I added it.
Thx to update.
> Add missing OnePlus One product ID : "6765"

- 51-android.rules
The deleted part of the rule actually blocks the HTC One S from being used, because it directly goes to "android_usb_rules_end"
> Making HTC One S work again

- 51-android.rules
USB ID `0bb4:0f87` already exists in `51-android.rules`. Simply added the device name `Sensation`.
> added device name for HTC Sensation 0bb4:0f87

- 51-android.rules
The device shows up as
Bus 002 Device 002: ID 0fce:01bb Sony Ericsson Mobile Communications AB D5803 [Xperia Z3 Compact] (MTP mode)
in `lsusb` output.
> Add rule for Sony Ericsson Xperia Z3 Compact.

- 51-android.rules
I use the SGS3 SHW-M440S which is a 3G version only sold in South Korea. I have added a comment line above the relevant USB ID in `51-android.rules`.
> added text string for Samsung Galaxy S3 SHW-M440S Korean version

- 51-android.rules
Reduce the amount of repeated code referring to debug AND fastboot by
using just 1 enviroment variable in the ID test section of the script.
Add an "android" SYMLINK so developers know device is connected, but
the real debug SYMLINK is supposed to be "android_adb" as per docs.
> Code and repetition reduction

- 51-android.rules
- ubuntu/51-android.rules
Hi, I've got another one for you :).
Proof: https://dl.dropboxusercontent.com/u/93551/2016-04-08%2017.12.20.jpg
I've added the VendorId to the ubuntu file too. BTW, there's dangling whitespace there, I just followed the convention ;).
I've got another Micromax device (phone) that does not use that VendorId but one of the Google ones `18d1:d002`. Looks like they finally bothered to buy an ID.
> Add Micromax P702

- 51-android.rules
Proof: https://dl.dropboxusercontent.com/u/93551/2016-04-22%2013.01.58.jpg
Had to [root](http://forum.xda-developers.com/mediapad-m2/how-to/guide-unlock-bootlader-twrp-root-huawei-t3322340) that thing.
Feels like a cheap 3rd gen iPad but with lower DPI.
I don't get why Android tablets assume that I would use them horizontally.
> Add HUAWEI MediaPad M2-A01L

- ubuntu/51-android.rules
I guess the idVendor could be the same for all fire tablets. I only tested it with the new ($50) amazon fire tablet.
> Added rule for amazon fire tablet 7inch

- 51-android.rules
Discovered by @tibocapo and reported as #88. Issue was resolved by suggesting a manual fix.
This pull request fixes the issue for Honeywell/Foxconn and Zebra (which also used a rule structure that was prone to that bug.
> Fix goto issues for Honeywell/Foxconn and Zebra

- 51-android.rules
Based on model D6503
mtp user access worked after this change. I haven't tested the adb stuff yet. (so I'm not sure if adb_adbfast is correct)
> Added Sony Xperia Z2

- 51-android.rules
- adb_usb.ini
6108 is the usb connection sharing mode - but that is probably not needed
adb and fastboot were both working correctly after changes
also added them to https://usb-ids.gowdy.us/mods/UD/2b0e 
so they will show up in lsusb in future
> added lex720 [LePro3] by vendor leeco and deleted spurious lines for Yota

- README.md
Currently the ubuntu steps listed to clone using git.
This method causes authentication errors when realistically is not necessary for average user
Just use the link provided from clicking the 'clone or download' link.
> Readme: Fix repo cloning for Ubuntu

- 51-android.rules
file use **smart** quotation.
There quotation marks in this will destroy the syntax of the text editor.
> fixed: quotation to ascii

- 51-android.rules
OnePlus 3T running Oxygen OS Oreo changes IDs for every USB mode.
> Add special rules for OnePlus 3T running Oreo

- 51-android.rules
+ add oneplus 3 device, seems can not be recognized by ubuntu(17.10)
after updated to oreo.
* format ZTE according to rules
> add Oneplus3 device(Oreo)

- 51-android.rules
My idProduct of PH-1 was different from what was already registered, so I added it.
> add another idProduct for Essential PH-1

- README.md
Hi it's a minor README change, please have a look - 
Ubuntu instructions - some commands were using `$PWD` while some were already inside the directory -  made the instructions consistent for copy-paste ease
Added a `mkdir` which should address the problem raised [here](https://github.com/M0Rf30/android-udev-rules/commit/da35e0345cfe50e45dcc6c8d6d841c71117cf899#commitcomment-26559262).  I had the same issue where the sysusers.d directory didn't exist.
> Ubuntu instructions - minor consolidation

- README.md
Previous to this addition, the symbolic link did not work. However this will work on most Linux systems.
This closes M0Rf30/android-udev-rules#144
> Fixed symbolic link

- README.md
Actually removes the footnote from the README.md about the adb_usb.ini file. This has been overlooked with the previous commit (d19fdc3815f507e3a1a142b3423dbacdb48ca80d).
> Remove adb_usb.ini footnote

- 51-android.rules
The GOTO definition is wrong for nVidia. It says Motorola (someone probably forgot to edit after copy-pasting).
> Fix nVidia label definition.

- 51-android.rules
Hi. My Essential Phone is labeled as `2e17:c032` ([and I’m not the only one](//forum.xda-developers.com/essential-phone/help/fastboot-commands-t3950106)).
Variant: Telus
The syntax should be ok, but please verify.
PS: Just ignore the comment on the commit, it’s not actually a fix
> Essential Phone PH-1 is also known as `2e17:c032`

- rpm/android-udev-rules.spec
Installed and verified on Fedora 30.
Test compiled with mock for epel-7 and  opensuse-tumbleweed as well without any problems.
> Add RPM spec file to allow building rpm packages

- 51-android.rules
Hi,
This adds support to Huawei P10 Lite to udev rules.
`Bus 001 Device 016: ID 12d1:107e Huawei Technologies Co., Ltd. WAS-LX1A`
Correct me if I lack anything here.
Thanks
> Adds support for Huawei P10 Lite to udev rules

- 51-android.rules
Line 458-460 are already taking care of this:
458 # Qualcomm
459 ATTR{idVendor}!="05c6", GOTO="not_Qualcomm"
460 ENV{adb_user}="yes"
Test: adb device with pid 05c6 still working
> Removed duplicate entry for Qualcomm (05c6)

- 51-android.rules
Reading through issue #163, noted that the vendor ID seen is 0955, and not 0995.
Also note that some digging shows 0955:7000 is also a Toshiba Folio.
It may be probable that the nvidia chip used here was used in more than one product.
Checking internet, found two references to Nvidia, 0955:7000 for fastboot
and another that mentions 0955:7100 which presumably is another mode but not described (therefore assuming maybe a user or development mode).
Squash merge is ok.
> nvidia corrected to 0955, should close issue #163

- 51-android.rules
There were a few instances of idVendor being checked without
idProduct being verified first. Re-coded to ensure idVendors
had an idProduct check first.
SYMLINK+=android_adb can be also done too with ENV{adb_adb}.
Shorten adb_fast to exclude adb_user, adb_adbfast does both.
Squash merge okay.
> Ensure all idProduct are guarded by a preceeding idVendor.

- 51-android.rules
Added additional check for attribute 'add' at the top to skip everything if this is not an add or usb addition.
Also noted a duplicate in HTC, plus needs a correction:
=0c01 for mass storage, and
=0c02 for development
I'm pretty sure the G1 added twice already needed to be corrected.
Do fewer tests for Intel phones and don't assume other stuff is.
This can be squash-merged.
> Exit earlier if not 'add'. ...and reduce some tests further.

- 51-android.rules
Some devices aren't likely going to ever be android devices
such as hubs or printers, therefore skip tests and move on.
Removed default ENV{adb_user}="yes" for several vendors and
set yes only if matches vendor and product-mode. These need
to be tested-out, therefore just change some for now, later
change the rest. ...android.rules should check for android,
and leave mtp mode for another set of rules devoted to mtp.
also relates to issue #164
squash merge okay.
> Skip hubs and printers. avoid assuming android developer mode

- 51-android.rules
Uncovered by #164
```
/usr/lib/udev/rules.d/51-android.rules:108 The line takes no effect, ignoring.
/usr/lib/udev/rules.d/51-android.rules:109 The line takes no effect, ignoring.
/usr/lib/udev/rules.d/51-android.rules:179 The line takes no effect, ignoring.
/usr/lib/udev/rules.d/51-android.rules:281 The line takes no effect, ignoring.
/usr/lib/udev/rules.d/51-android.rules:339 The line takes no effect, ignoring.
/usr/lib/udev/rules.d/51-android.rules:346 The line takes no effect, ignoring.
/usr/lib/udev/rules.d/51-android.rules:353 The line takes no effect, ignoring.
```
> Fix some typos

- 51-android.rules
My SHIELD Tablet (RoW) has this ID when connected.
Also changed into lowercase for consistency.
> Update SHIELD Tablet product ID

- 51-android.rules
Verified on NixOS Linux.
From:
```
~ $ fastboot devices
no permissions; see [http://developer.android.com/tools/device.html]    fastboot
```
To:
```
~ $ fastboot devices
181###V01500### fastboot
```
And fastboot features working as expected.
> Add Razer Phone 2 fastboot mode

- 51-android.rules
This is how the [Zebra TC72](https://www.zebra.com/us/en/products/mobile-computers/handheld/tc72-tc77-series-touch-computer.html) appears from `lsusb`:
```
Bus 001 Device 021: ID 05e0:2106 Symbol Technologies
```
With this new rule installed, I'm able to use the TC72 with Android Studio.
> Add Zebra TC72 support

- 51-android.rules
Here's the output of `lsusb`:
```
Bus 001 Device 024: ID 045e:0c26 Microsoft Corp. Surface Duo
```
With this change I am able to use the device over adb
> Add a rule for Microsoft Surface Duo

- 51-android.rules
1 - The Tab 210 was mentioned but wasn't added yet. Including it here.
2 - Also add multiple phone pointers with another symlink to /dev/android%n based on Motorola pointer.
3 - There is one Idea phone that used the same idVendor as Google. Best to move it where it can actually be seen and recognized.
> Add Iconia Tab 210 (ref #204)

- 51-android.rules
It looks like a typo in the rules for MediaTek.
It was preventing my Umidigi A3 (0e8d:201c) from being detected.
I tested the changed rules and it now registers properly.
> fix MediaTek rules

- 51-android.rules
ZenFone 2 uses Google IDs for modes where MTP is available, but when only ADB is available, it uses Intel's 0x0807, 0x0a5d.
> Add Asus ZenFone 2 (Sideload in Recovery)

- 51-android.rules
As seen in [0], the accessory mode uses the 2d00 id.
Access to this configuration is needed for Android Open Accessory[1],
specifically for WebAOA[2] which allows users to control a connected
device via this protocol.
[0] https://cs.android.com/android/platform/superproject/+/2aa85be00e485a06fb5a86276a2344ef1182e2af:system/core/rootdir/init.usb.rc;l=49-56
[1] https://source.android.com/devices/accessories/protocol
[2] https://source.android.com/compatibility/tests/development/android-test-station/ats-user-builds
> Add Android accessory mode

- 51-android.rules
Tested that it works with `adb` and `scrcpy`
Please let me know if the order of devices should be changed
> Add Sony Ericsson Xperia Z Ultra

- 51-android.rules
> Hey, but didn't you do this already in #199?
No! I only added fastboot support as it was the only thing I needed at the time. I was working on a non-android Linux on the phone, and didn't use the phone in a way that involved ADB.
Still using NixOS Linux
**Before**:
```
~ $ adb shell
adb: insufficient permissions for device
See [http://developer.android.com/tools/device.html] for more information
```
**After**:
```
~ $ adb shell echo ok!
ok!
```
> Add Razer Phone 2 ADB mode

- 51-android.rules
This Android-based micro-four-thirds camera device, sold only in mainland
China, is identifying itself in lsusb as:
05c6:9091 Qualcomm, Inc. Intex Aqua Fish & Jolla C Diagnostic Mode
Therefore, it's placed under the Qualcomm section.
> Add Yongnuo YN450M

- 51-android.rules
Thank you for your work on these udev rules! They make all our lives easier :smile: 
ADB mode is handled by the recently added line for the Realme 8.
> Add OPPO Watch fastboot mode

- 51-android.rules
This patch was tested with Nubia Z11 miniS (NX549J), but should also work with more than fifty `NX***`-ish phones branded under ZTE, Nubia or RedMagic ([full list](https://www.nubia.com/active/nonguaranteedprice.html)).
> Add ZTE Nubia series

- 51-android.rules
Add device IDs for internal modems used in ZTE MF286[,A,D,R] series of modems. Tested on modems plugged directly into the PC.
> Add rules for ZTE MF286* series internal modems

- 51-android.rules
With the previous entry the rules did not allow for fastboot identification. Tested on the Pixel C.
> Change fast to adbfast for Pixel C

- 51-android.rules
Tensor Pixels (Pixel 6/6A/6 Pro) have dropped RNDIS for CDC NCM and have a different product IDs for the modes.
18d1:4eeb for CDC NCM
18d1:4eec for CDC NCM and ADB
> Add product ID for CDC NCM and ADB for Tensor Google Pixels

- README.md
- install.sh
Fixes the automated install script. The previous implementation always gets the root user added to the adbusers group instead of the username of the regular account (the one we usually use normally).
> Fix get current user instead of root on the automatic install script

- 51-android.rules
This is a followup to https://github.com/M0Rf30/android-udev-rules/pull/247.
It rewrites the Polar vendor to an actual section and adds the Polar M600 product for adb and fastboot mode.
> feat: Rewrite Polar vendor and add Polar M600 product.

- 51-android.rules
My `Wileyfox Swift 2 Plus` has been identified as a `Qualcomm` vendor with `idProduct` `0001`
> add Wileyfox Swift 2 Plus

- 51-android.rules
Help resolve issue #250 by excluding several HID class devices which are confused with being android devices.
> issue 250 - exclude several Sony and Microsoft USB controllers, VR, BT

- rpm/android-udev-rules.spec
I made small update to RPM spec. It now creates `adbusers` group and also reloads/restarts udev rules on RPM install and remove.
Tested on my Fedora 36 laptop with Google Pixel 6a. After RPM install `scrcpy` runs correctly without root permissions.
> Add android-udev.conf to RPM spec

- 51-android.rules
Hello there!
I've recently changed PCs, and this new one doesn't have a WiFi card + I'm waiting for an Ethernet cable. 
In the meantime I use my phone as WiFi receiver, and I noticed it works in all USB modes except USB tethering.
This line adds support for it.
`adb devices` shows the phone as `device` and I've been able to run `adb shell` or have Expo communicate with my device smoothly.
Note that I can't say for sure it'll work with the 5G edition of Nord N10s, as I don't have the device to test it, hence why I specified it's the older model.
Have a good day~
> Add support for OnePlus Nord N10 4G in USB tethering mode

- 51-android.rules
- README.md
- debian/changelog
- debian/control
- debian/copyright
- debian/rules
- rpm/android-udev-rules.spec
See individual commits for details.
I'm not entirely sure which one of `adb_adb` and `adb_user` would suit better this untested device. I also assumed the license is GPL v3 (or later), as that's what was specified in the RMP|.deb metadata.
If that isn't right (or if any other part should be corrected) I can spin up a v2. Someone else amending the commits is also fine with me.
> Meizu M6T and miscellaneous improvements

- 51-android.rules
This code should run faster than the existing code after a device is found, by using GOTO LABEL (which is basically a string search of text).
The existing code right now (before this patch) may end up doing several more unnecessary value checks while dropping-down through next lines of code.
> GOTO next LABEL after device found (for a faster rules script).

- 51-android.rules
This hasn't been tested yet btw
@M0Rf30 There aren't that many changes, but I'd appreciate a review nonetheless. Also, I'd prefer a fast-forward merge – I tried submitting two separate PRs but GitHub wouldn't act how I wanted it to. (Of course after I test that if everything works as expected)
@JoesCat Was there any reason you didn't add fastboot without adb (`LABEL="fast"`) together with all the other options?
As far as I understand it, adb is a userspace component – runs under Android or in the recovery and requires Linux (the kernel) – while traditionally (before fastbootd became a thing), fastboot was running on bare metal only – without an OS. So I'd expect that most older devices would never have adb and fastboot active at the same time.
> Fixup for the recent refactor, support for fastboot without adb and Moto Z3 Play

- 51-android.rules
Added direct GOTOs based on detailed info by alpenb (see issue#259) which shows various adb modes and their idProduct values. The Umidigi F1 appears to also conflict with a fastboot (vs a debug for Motorola E22i).
Also scraped several MediaTek idProducts from libmtp for more adb connections for these devices = MT65xx/67xx.
Expanded adbcdc for debugging purposes, and added some cdc comments based on some info read here about 0e8d:2000 and cdc_acm mode:
https://forum.xda-developers.com/t/tutorial-how-to-setup-sp_flash_tool_linux-mtk-mediatek-soc.3160802/page-5
> Add MediaTek Moto E22i, MT65xx/67xx

- 51-android.rules
Aligned some codes based on earlier commenting.
included gentoo's 22d9:2774=mass,adb and gionee 271d:3f11=mass,adb:
https://forums.gentoo.org/viewtopic-t-1067416-start-0.html
Also scraped some idProducts from linux-usb.org which had several references for 3T,5T,6 for idProduct={4ee7,904d,904e}
Also scraped some further idProducts from libmtp:
OnePlus One (6765=mtp,adb, 6764=mtp), issue112=9012=mtb,adb
> Modify generic adb to be more specific adb GOTOs for Oppo and OnePlus

- 51-android.rules
Also including these as comments:
18d1:4ee1=mtp, https://bugs.mageia.org/show_bug.cgi?id=28860
Fairphone 2, original OS: (plan to switch it to /e/ or sailfish)
Booted normally, not in 51-android.rules:
ID 05c6:f006 Qualcomm, Inc.
Off, charging:
ID 2ae5:f000 Fairphone B.V. 2 (Mass storage)
https://forum.fairphone.com/t/wanted-debian-stretch-udev-rule-for-fp-fairphone-2-with-openos-7-1-2-v19-02-1/48776
05c6:901d=mtp - with openOS.
> Modify generic adb to be more specific adb GOTOs for Fairphone

- 51-android.rules
Some additional idProduct values found in linux-usb.org
and libmtp datapoints also provided some more useful info, plus it's issue92
> Modify generic adb to be more specific adb GOTOs for Xiaomi

- 51-android.rules
Enter values as per core phone.
Seeing device hunter webpage, changed false positives to ony pass 6???
```
samsung galaxy core sm-g386w
teher
04e8:6863 Samsung Electronics Co., Ltd Galaxy series, misc. (tethering mode)
dbg,tethering
Bus 001 Device 009: ID 04e8:6864 Samsung Electronics Co., Ltd GT-I9070 (network tethering, USB debugging enabled)
adb,mtp
Bus 001 Device 008: ID 04e8:6860 Samsung Electronics Co., Ltd Galaxy series, misc. (MTP mode)
Bus 001 Device 010: ID 04e8:6860 Samsung Electronics Co., Ltd Galaxy series, misc. (MTP mode)
ptp
Bus 001 Device 010: ID 04e8:6865 Samsung Electronics Co., Ltd Galaxy (PTP mode)
ptp,adb
Bus 001 Device 011: ID 04e8:6866 Samsung Electronics Co., Ltd Galaxy (debugging mode)
```
> Add/edit Samsung Core

- 51-android.rules
Added values according to Motorola G3.
```c
adb,charging
Bus 001 Device 014: ID 22b8:2e81 Motorola PCS
charging
Bus 001 Device 040: ID 22b8:2e82 Motorola PCS
adb,mtp
Bus 001 Device 018: ID 22b8:2e76 Motorola PCS
mtp
Bus 001 Device 040: ID 22b8:2e82 Motorola PCS
adb,ptp
Bus 001 Device 031: ID 22b8:2e84 Motorola PCS
ptp
Bus 001 Device 039: ID 22b8:2e83 Motorola PCS
adb,rndis
Bus 001 Device 027: ID 22b8:2e25 Motorola PCS
rndis
Bus 001 Device 038: ID 22b8:2e24 Motorola PCS
adb, audio sources
Bus 001 Device 028: ID 18d1:2d03 Google Inc.
audio sources
Bus 001 Device 035: ID 18d1:2d02 Google Inc.
adb,midi
Bus 001 Device 029: ID 18d1:4ee9 Google Inc.
midi
Bus 001 Device 034: ID 18d1:4ee8 Google Inc.
```
Fetched some related idProducts from libmtp.
> Add Motorola G3, edit some other Motorola values

- 51-android.rules
compress list and add more colected info
> chore: use more specific adb GOTOs for ZTE (#278)

- 51-android.rules
also merged additional info found in linux-usb.org, and libmtp idProduct values, and device hunter values.
> chore: use more specific adb GOTOs for Qualcom & nVidia (#279)

- 51-android.rules
merge in idProduct details from linux-usb.org, device hunter, libmtp
> chore: use more specific adb GOTOs for Google

- 51-android.rules
merge info from linux-usb.org, libmtp, device-hunter, and also
http://www.joescat.com/linux/android_rules.html
Google Ion:
```c
Mass Storage, Mass Storage+Debug
Bus 001 Device 006: ID 0bb4:0c01 HTC (High Tech Computer Corp.) Dream / ADP1 / G1 / Magic / Tattoo / FP1
Bus 002 Device 002: ID 0bb4:0c02 High Tech Computer Corp. Magic (Debug)
```
> chore: use more specific adb GOTOs for htc

- 51-android.rules
merge in some idProduct details from linux-usb.org and device hunt
> chore: use more specific adb GOTOs for lg

- 51-android.rules
Reduce several generic links down to more specifics by changing "assumed match" due to vendor code, to "assumed exits" using GOTO="android_usb_rules_end". This should help reduce false positives that perhaps should be handled elsewhere like cameras, keypads, keyboards, mice, or other devices, etc, etc, etc.
Some vendor info is very ambigous and needs more info therefore commented-out code (needs more info).
Some vendors left as-is since they appear specific to a product type and it might break a line of something which may be better left for now, looked at in future.
merged in some idProduct details from linux-usb.org, device hunt, and also libmtp.
Cleaned up some commenting for more consistency.
> chore: use more specific adb GOTOs for misc

- 51-android.rules
initial patch was to add android links, however, based on looking at libmtp these are both mtp, therefore changed these to adb+mtp, while the mtp-only product was dropped and left for libmtp to handle since it appears there is no adb for this. More details given in issue #46
> chore: modify BQ device as adb+mtp, or mtp

- 51-android.rules
Thanks to Piotr Masłowski (mskiptr) for the detailed work done here.
Please see issue https://github.com/M0Rf30/android-udev-rules/pull/269
> feat: add Samsung Galaxy A5

- 51-android.rules
Details as seen in issue #269 - Samsung Galaxy A5 (2016)
> feat: add 04e8:685d ODIN link used instead of fastboot by Samsung

- 51-android.rules
Thanks to Zesko (read issue #287) for pointing-out several errors that should be fixed to prevent filling log reports with error messages.
seen as per command-line: journalctl --no-pager -p err -b --output=cat
> fix: fix code due to journalctl output errors

- 51-android.rules
resolves issue #293 and issue #296 for fastboot.
Thanks to @icyrockcom and @fuyukihidekii
Also tidy-up some vendor values, and convert the Motorola section from default accept everything to default drop unknown codes. Non-adb related vendor codes drops through, to be surrendered to other USB rules.
> fix: Motorola adbfast code, also sort codes and use default drop

- 51-android.rules
Looked at cleaning up a little more with intention of adding another vendor from default blanket accept, to default drop unknown values.
Did some comparisons and removed these vague `SYMLINK+="android_adb"` for 9039, 904e.
[9039 appears to be adb](https://xiaomi.eu/community/threads/xiaomi-mi-2s-not-showing-up-on-android-sdk-debugging.20631/post-169312)
0368 was also another vague `SYMLINK+="android_adb"` link, but appears to be adb
[mentioned as mtp,adb here](https://www.drivermax.com/Android-Composite-ADB-Interface-Google-Inc_USB-VID-2717-PID-0368-MI-02-7_0_0000_00000-2013-03-22-1235360-driver.htm) and [here](https://www.debian-fr.org/t/xiaomi-mi3-mal-detecte-par-debian-jessie/66921/4).
Several modes also described [here](https://www.debian-fr.org/t/xiaomi-mi3-mal-detecte-par-debian-jess …
> chore: use more specific adb GOTOs for XiaoMi

- 51-android.rules
Add Alcatel 5024L - aka Alcatel 1S - tested on voidlinux and working with scrcpy
Linux achar-void 6.5.13_1 #1 SMP PREEMPT_DYNAMIC Thu Nov 30 23:19:06 UTC 2023 x86_64 GNU/Linux
> Added Alcatel 5024L

- 51-android.rules
They all share the same vendor ID, checked with S T8100 tablet
Change-Id: Ia2da9a4be5cdbb6c756bc05267006bc2ee230c07
> feat: Add Allwinner fastboot rule

- 51-android.rules
With connected Pixel 7 in a fastboot mode, lsusb outputs:
`Bus 001 Device 009: ID 18d1:4ee0 Google Inc. Nexus/Pixel Device (fastboot)`
Tested, works.
> feat: Add fastboot Google Pixel 7

- 51-android.rules
The data was moved in [5e309b92483]
[5e309b92483]: https://android.googlesource.com/device/google/wahoo/+/5e309b924830644827182e039e915e5ba314a81f%5E%21/
> update link to google source

- 51-android.rules
with https://github.com/the-modem-distro/pinephone_modem_sdk , it possible to enable adb on this modem (id didnt changed)
```
ID 2c7c:0125 Quectel Wireless Solutions Co., Ltd. EC25 LTE modem
```
> add Quectel EC25

- 51-android.rules
as the comment above states: `2d04=accessory,audio`
Not sure if this was removed/left out for some reason in the past... 
but I needed it to make AOA work.
> feat: Add support for Android Open Accessory device 2d04

- rpm/android-udev-rules.spec
Without proper spec versioning, package managers can get confused over which build to install, causing inconsistent behavior. The spec should be versioned each time the files are changed.
> fix: version the spec

- 51-android.rules
Device info: https://www.fibocom.com/en/Products/5G-FG180-NA.html
> add support for Fibocom FG180 modem

- 51-android.rules
It is spelled Tattoo
https://en.wikipedia.org/wiki/HTC_Tattoo
> [correction] Fix spelling of HTC "Tatoo" -> Tattoo

- 51-android.rules
as described in issue #345 as 12d1:1c2c.
This may just be adb and likely everything else done through bluetooth
more searching found: https://devicehunt.com/view/type/usb/vendor/12D1 and added comments plus values for 1053=ptp, and 1054=ptp+adb
OPPO watch=22d9:2769 already marked as adb, therefore updated comment.
> chore: update Huawei watch and add comment about OPPO watch

- 51-android.rules
Info for adb and fastboot access in issue #347
> feat: Add LG V20

- 51-android.rules
Notes: Imported issue #352 and added it to Amazon group.
Closes #352
> feat: Add Amazon Fire HD 8 10th gen (onyx)
