51-android.rules
comments are only allowed at the start of a line
=> fix syntax

51-android.rules
Seems to work...
Tried with a friend's OnePlus Two...
=> Add rules for OnePlus Two

51-android.rules
Fix issue #72, and fix or improve a few lines.
=> Mainly fix issue #72 to exclude bluetooth dongle

README.md
This rework should look a little better in the README and has some minor fixes in the commands. I can change it from `sudo` based to root login if people are interested.
Might work better to remove Ubuntu references...
=> Reworked most of the README

51-android.rules, ubuntu/51-android.rules
=> Cleanup whitespace and wording

51-android.rules, ubuntu/51-android.rules
Sourced from https://developer.android.com/studio/run/device.html
=> Added Wileyfox and YU.

ubuntu/51-android.rules
I have added support to BQ Devices
=> Add BQ Devices

51-android.rules
Add New Vendor IUNI and IUNI U3 Device
Add Xiaomi 4c Device
Test All ok
=> Add Xiaomi 4c and IUNI Device

51-android.rules
YotaPhone2's idProduct is f003=normal, 9139=debug.
correct it.
=> correct idProduct

ubuntu/51-android.rules
I have added support to Nokia X device
=> Add Nokia X

51-android.rules
As my OnePlus 3T was not recognized, I added it. At least it works for my device :)
=> Added OnePlus 3T

51-android.rules
=> Add LG G2 mini D620r

51-android.rules
Tested on Gentoo, udev (233), Android Studio (2.3.2)
=> Adding Xperia Z3 (D6603) 

51-android.rules
Added Research in Motion section with BlackBerry DTEK60 codes, tested and working.
=> BlackBerry DTEK60

51-android.rules
Signed-off-by: YOUNG HO CHA <ganadist@gmail.com>
=> add product id to support intel reference boards

51-android.rules
Signed-off-by: YOUNG HO CHA <ganadist@gmail.com>
=> add product id for Xiaomi A1

README.md
=> systemd-sysusers not available on 16.04

51-android.rules
=> Added Xperia XZ

51-android.rules
=> Added LG90 D410 rules

51-android.rules
Add the standard GPLv3 header text to rules file.
=> Add GPLv3 header to rule file

51-android.rules
Added vendor sonim to bottom of the current list.
=> Add Sonim as vendor

51-android.rules
Reverts M0Rf30/android-udev-rules#120
=> Revert "Uncommented Dell idVendor line"

README.md
Had a little trouble following along. Hope this can help others too
=> Made README easier to follow along

README.md
See preview [here](https://github.com/hrj/android-udev-rules/tree/patch-1)
=> syntax highlight for shell commands in README

51-android.rules
Merging info found in other places. Squash merge okay.
=> Scanned other rules and updated vendor names, added Parrot

51-android.rules
Add rule for Xiaomi Redmi 8 Pro - closes #192
=> # RedMi 8 Pro by miguelromero

51-android.rules
=> Add three Sony Xperia ids

51-android.rules
I've tried to take comments from https://github.com/M0Rf30/android-udev-rules/pull/191 into account for this PR. Please comment if there is anything I've missed. The solution has been tested, and seem to work as expected both in normal, and debug mode.
=> Add support for Unitech EA630

51-android.rules
Bus 001 Device 088: ID 11ca:ca11 VeriFone Inc P630
Signed-off-by: Yaroslav Furman <Yaroslav.Furman@softeq.com>
=> Add VID for Verifone devices

51-android.rules
=> Add ZTE Blade A5 2020

install.sh
=> Remove dead code from install.sh

51-android.rules
This just adds vivo devices on udev rules for adb.
=> Add support for vivo devices

51-android.rules
Adds support for ADB and fastboot mode.
=> Add Polar M600

51-android.rules
...waiting for testing in issue@256
=> Kindle Fire 10

51-android.rules
oops! missed this earlier, remove it now.
squash merge is fine.
=> Printer found! Shouldn't set value while exiting script.

51-android.rules
Changed values according to comment section.
Compare values to linux-usb.org and also scraped several libmtp values.
=> Modify generic adb to be more specific adb GOTOs for Asus

51-android.rules
Add Alcatel 5024L - aka Alcatel 1S
=> feat: add Alcatel 5024L aka Alcatel 1S

51-android.rules
Support the fastboot mode of ASUS ZenWatch 2
Bus 003 Device 074: ID 0b05:7771 ASUSTek Computer, Inc. Android
=> feat: add ASUS ZenWatch 2

51-android.rules
Support the adb mode of Oculus Quest 2
Bus 002 Device 002: ID 2833:0186 Oculus Quest 2
=> feat: add Oculus Quest 2 (close #308)

51-android.rules
Verified that adb works with this rule
Bus 003 Device 011: ID 3360:201c MediaTek SHIFT5me
=> feat: add SHIFT5me

51-android.rules
Pico 4 VR Headset
https://www.picoxr.com/uk/products/pico4
=> Add Pico 4 VR Headset

51-android.rules
Support the UVC mode of Pixel Devices.
Fix #321
=> feat: add UVC for Pixel devices (close #321)

51-android.rules
Example lsusb output:
```
ID 17ef:201c Lenovo Lenovo Tab K10
```
=> Add Lenovo Tab K10

51-android.rules
https://www.gsmarena.com/sony_ericsson_xperia_play-3608.php
=> Add a rule for Xperia Play

51-android.rules
Add adb access for https://github.com/M0Rf30/android-udev-rules/issues/350
=> feat: add support for KAZAM Tornado 348
